### ISSUE TITLE
Color jump on color select

### ISSUE THREAD

**Issue by XilefTech** [namacha/python-magichue#13] opened 2019-11-06 21:02 UTC
I don't really know if this is really a bug or just a feature, I like to have but when I select a color with light.rgb, the color doesn't jump immediately, but it just fades. I would wish me a function that changes the color instantaniously.
I'm using the #7 fix branch.

Thanks Felix

**Comment by namacha** [comment] 2019-11-07 04:07
After setting color, does it fade to black? or its color changed with fading effect?

Maybe protocol on my device differs to the one on your bulb.  Which bulb do you use?

**Comment by XilefTech** [comment] 2019-11-07 13:46
Thanks for the quick reply 
I'm using [this](https://www.amazon.de/Controller-gesteuert-Dynamische-Farbwechsel-Fernbedienung/dp/B0772PGDFM/) controller and if I set a color, the stripes fade to that set color, but I want them to jump to that color. They don't fade to black or any other color (except the previously set one).
with the main branch, the colorchange wouldn't work, but as I exxplained everything works with the #7 branch

**Comment by namacha** [comment] 2019-11-07 14:31
Alright, I gonna buy the same bulb and work on update.  Although I’ve been busy recently, so please be patient.

**Comment by namacha** [comment] 2019-11-08 18:40
I did some tests with magichue led stripe, and found that behavior is in the specification.  However, there seems to be a some hack to change color immediately.
I will contain this hack in the future commit.  Please wait for a while.

**Comment by XilefTech** [comment] 2019-11-08 20:24
Okay thanks
I'm not in a hurry but hope you can make it possible soon

**Comment by namacha** [comment] 2019-11-12 10:47
Just committed updates.  I haven't merged commit to master branch and written README, but you can try it with feat-#13 branch.

To disable fading on color change, run codes as below.
```python
import magichue

l = magichue.Light('192.168.0.17')  # change address
l.allow_fading = False
l.rgb = (255, 0, 0)  # this should jump to red (but with a little delay).
```

I'd appreciate if you report a another bug or something.

![tape](https://user-images.githubusercontent.com/5038965/68666602-906ce180-0587-11ea-840d-29fceec21c4a.gif)

**Comment by XilefTech** [comment] 2019-11-13 22:39
Thanks a lot!
I'll try it out as soon as I can, but lately, I got very much to do with school :(

**Comment by XilefTech** [comment] 2019-11-20 16:56
I just found time to test it, and it works!

But there is a small problem, that when I'm using `light.allow_fading = False` I get a slight flickering on my stripes, like if you would turn them of and back on for a few millis. which is verry annoying. without `light.allow_fading = False` I don't get any of these artifacts.
I also noticed, that it takes a lot more time to change the colors than without.

**Comment by XilefTech** [comment] 2019-12-02 21:52
Sorry, if I'm impatient, but since I didn't get any answer for more than a week, I wanted to ask, If someone is actually working on the problem or at least just looked at it....

**Comment by namacha** [comment] 2019-12-03 14:27
I’m sorry for not responding sooner.  
 My bulb (same bulb as you I think) is working correctly, so I wonder if your network environment has problem.  Or there is no problem on your network, 
I want you to do some tests with your bulb to try to find out the cause of problem.  I will tell about tests later.

This is just a quick note, please excuse my brevity.

**Closed as completed** 2022-08-17 00:51 UTC
